# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
default_install_hook_types: [pre-commit, commit-msg]
verbose: true # Enable verbose output globally

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=3000
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args:
          - --fix
          - --show-fixes # Show what files were fixed
          - --verbose
        exclude: ^alembic/versions/
      - id: ruff-format
        verbose: true
        exclude: ^alembic/versions/
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
    files:
      - deployments/**
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2 # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks
