services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - ${PUBLIC_APP_PORT}:80
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
      - ADDRESS=${ADDRESS}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      # App
      LOG_LEVEL: ${LOG_LEVEL}
      AEGISCAN__API_URL: ${AEGISCAN__API_URL}
      AEGISCAN__API_ROOT_PATH: ${AEGISCAN__API_ROOT_PATH}
      AEGISCAN__APP_ENV: ${AEGISCAN__APP_ENV}
      AEGISCAN__DB_ENCRYPTION_KEY: ${AEGISCAN__DB_ENCRYPTION_KEY} # Sensitive
      AEGISCAN__DB_SSLMODE: ${AEGISCAN__DB_SSLMODE}
      AEGISCAN__DB_URI: ${AEGISCAN__DB_URI} # Sensitive
      AEGISCAN__PUBLIC_API_URL: ${AEGISCAN__PUBLIC_API_URL}
      AEGISCAN__PUBLIC_APP_URL: ${AEGISCAN__PUBLIC_APP_URL}
      AEGISCAN__SERVICE_KEY: ${AEGISCAN__SERVICE_KEY} # Sensitive
      AEGISCAN__SIGNING_SECRET: ${AEGISCAN__SIGNING_SECRET} # Sensitive
      AEGISCAN__ALLOW_ORIGINS: ${AEGISCAN__ALLOW_ORIGINS}
      AEGISCAN__AUTH_TYPES: ${AEGISCAN__AUTH_TYPES}
      AEGISCAN__AUTH_ALLOWED_DOMAINS: ${AEGISCAN__AUTH_ALLOWED_DOMAINS}
      AEGISCAN__AUTH_MIN_PASSWORD_LENGTH: ${AEGISCAN__AUTH_MIN_PASSWORD_LENGTH}
      AEGISCAN__SETTING_OVERRIDE_SAML_ENABLED: ${AEGISCAN__SETTING_OVERRIDE_SAML_ENABLED}
      AEGISCAN__EXECUTOR_URL: ${INTERNAL_EXECUTOR_URL}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      USER_AUTH_SECRET: ${USER_AUTH_SECRET}
      # SAML SSO
      SAML_IDP_METADATA_URL: ${SAML_IDP_METADATA_URL}
      # Temporal
      TEMPORAL__CLUSTER_URL: ${TEMPORAL__CLUSTER_URL}
      TEMPORAL__CLUSTER_QUEUE: ${TEMPORAL__CLUSTER_QUEUE}
      TEMPORAL__CLUSTER_NAMESPACE: ${TEMPORAL__CLUSTER_NAMESPACE}
      TEMPORAL__TASK_TIMEOUT: ${TEMPORAL__TASK_TIMEOUT}
      TEMPORAL__API_KEY: ${TEMPORAL__API_KEY}
      # Migrations
      RUN_MIGRATIONS: "true"
      # Remote registry
      AEGISCAN__ALLOWED_GIT_DOMAINS: ${AEGISCAN__ALLOWED_GIT_DOMAINS}
      AEGISCAN__REMOTE_REPOSITORY_PACKAGE_NAME: ${AEGISCAN__REMOTE_REPOSITORY_PACKAGE_NAME}
      AEGISCAN__REMOTE_REPOSITORY_URL: ${AEGISCAN__REMOTE_REPOSITORY_URL}
      # AI
      AEGISCAN__PRELOAD_OSS_MODELS: ${AEGISCAN__PRELOAD_OSS_MODELS}
      OLLAMA__API_URL: ${OLLAMA__API_URL}
      # Local registry
      AEGISCAN__LOCAL_REPOSITORY_PATH: ${AEGISCAN__LOCAL_REPOSITORY_PATH}
      AEGISCAN__LOCAL_REPOSITORY_ENABLED: ${AEGISCAN__LOCAL_REPOSITORY_ENABLED}
    volumes:
      - ./aegiscan:/app/aegiscan
      - ./registry:/app/registry
      - ./alembic:/app/alembic
      - ${AEGISCAN__LOCAL_REPOSITORY_PATH}:/app/local_registry
    depends_on:
      - ollama
      - executor

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      AEGISCAN__API_ROOT_PATH: ${AEGISCAN__API_ROOT_PATH}
      AEGISCAN__API_URL: ${AEGISCAN__API_URL}
      AEGISCAN__APP_ENV: ${AEGISCAN__APP_ENV}
      AEGISCAN__DB_ENCRYPTION_KEY: ${AEGISCAN__DB_ENCRYPTION_KEY} # Sensitive
      AEGISCAN__DB_SSLMODE: ${AEGISCAN__DB_SSLMODE}
      AEGISCAN__DB_URI: ${AEGISCAN__DB_URI} # Sensitive
      AEGISCAN__PUBLIC_API_URL: ${AEGISCAN__PUBLIC_API_URL}
      AEGISCAN__EXECUTOR_URL: ${INTERNAL_EXECUTOR_URL}
      AEGISCAN__SERVICE_KEY: ${AEGISCAN__SERVICE_KEY} # Sensitive
      AEGISCAN__SIGNING_SECRET: ${AEGISCAN__SIGNING_SECRET} # Sensitive
      # Temporal
      TEMPORAL__CLUSTER_URL: ${TEMPORAL__CLUSTER_URL}
      TEMPORAL__CLUSTER_QUEUE: ${TEMPORAL__CLUSTER_QUEUE}
      TEMPORAL__CLUSTER_NAMESPACE: ${TEMPORAL__CLUSTER_NAMESPACE}
      TEMPORAL__API_KEY: ${TEMPORAL__API_KEY}
      # Local registry
      AEGISCAN__LOCAL_REPOSITORY_PATH: ${AEGISCAN__LOCAL_REPOSITORY_PATH}
      AEGISCAN__LOCAL_REPOSITORY_ENABLED: ${AEGISCAN__LOCAL_REPOSITORY_ENABLED}
    volumes:
      - ./aegiscan:/app/aegiscan
      - ./registry:/app/registry
      - ${AEGISCAN__LOCAL_REPOSITORY_PATH}:/app/local_registry
    command: ["python", "aegiscan/dsl/worker.py"]

  executor:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8265:8265
      # NOTE: Unit tests in `test_workflows.py` need
      # to connect to the executor directly
      - 8001:8000
    environment:
      # Common
      LOG_LEVEL: ${LOG_LEVEL}
      AEGISCAN__APP_ENV: ${AEGISCAN__APP_ENV}
      AEGISCAN__DB_ENCRYPTION_KEY: ${AEGISCAN__DB_ENCRYPTION_KEY} # Sensitive
      AEGISCAN__DB_SSLMODE: ${AEGISCAN__DB_SSLMODE}
      AEGISCAN__DB_URI: ${AEGISCAN__DB_URI} # Sensitive
      AEGISCAN__SERVICE_KEY: ${AEGISCAN__SERVICE_KEY} # Sensitive
      AEGISCAN__SIGNING_SECRET: ${AEGISCAN__SIGNING_SECRET} # Sensitive
      # Registry
      AEGISCAN__ALLOWED_GIT_DOMAINS: ${AEGISCAN__ALLOWED_GIT_DOMAINS}
      AEGISCAN__REMOTE_REPOSITORY_URL: ${AEGISCAN__REMOTE_REPOSITORY_URL}
      AEGISCAN__REMOTE_REPOSITORY_PACKAGE_NAME: ${AEGISCAN__REMOTE_REPOSITORY_PACKAGE_NAME}
      AEGISCAN__UNSAFE_DISABLE_SM_MASKING: ${AEGISCAN__UNSAFE_DISABLE_SM_MASKING:-false}
      # Email
      AEGISCAN__ALLOWED_EMAIL_ATTRIBUTES: ${AEGISCAN__ALLOWED_EMAIL_ATTRIBUTES}
      # AI
      AEGISCAN__PRELOAD_OSS_MODELS: ${AEGISCAN__PRELOAD_OSS_MODELS}
      OLLAMA__API_URL: ${OLLAMA__API_URL}
      # Local registry
      AEGISCAN__LOCAL_REPOSITORY_PATH: ${AEGISCAN__LOCAL_REPOSITORY_PATH}
      AEGISCAN__LOCAL_REPOSITORY_ENABLED: ${AEGISCAN__LOCAL_REPOSITORY_ENABLED}
    volumes:
      - ./aegiscan:/app/aegiscan
      - ./registry:/app/registry
      - ${AEGISCAN__LOCAL_REPOSITORY_PATH}:/app/local_registry
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "aegiscan.api.executor:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_SERVER_API_URL: ${NEXT_SERVER_API_URL}
        NODE_ENV: ${NODE_ENV}
    container_name: ui
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_AUTH_TYPES: ${AEGISCAN__AUTH_TYPES}
      NEXT_SERVER_API_URL: ${NEXT_SERVER_API_URL}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/.next:/app/.next
      - ./frontend/node_modules:/app/node_modules
    attach: false

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${AEGISCAN__POSTGRES_USER}
      POSTGRES_PASSWORD: ${AEGISCAN__POSTGRES_PASSWORD}
    volumes:
      - core-db:/var/lib/postgresql/data

  temporal_postgres_db:
    image: postgres:13
    container_name: temporal_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TEMPORAL__POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEMPORAL__POSTGRES_PASSWORD}
    volumes:
      - temporal-db:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:${TEMPORAL__VERSION}
    container_name: temporal
    restart: unless-stopped
    ports:
      - 7233:7233
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${TEMPORAL__POSTGRES_USER}
      - POSTGRES_PWD=${TEMPORAL__POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=temporal_postgres_db
      - LOG_LEVEL=warn
    depends_on:
      - temporal_postgres_db

    attach: false

  temporal_ui:
    image: temporalio/ui:${TEMPORAL__UI_VERSION}
    container_name: temporal_ui
    ports:
      - 8080:8080
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    depends_on:
      - temporal
    attach: false

  ollama:
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA__VERSION}
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

volumes:
  core-db:
  temporal-db:
  ollama:
