name: Lint Python

on:
  pull_request:
    paths:
      - aegiscan/**
      - registry/**
      - tests/**
      - pyproject.toml
      - .github/workflows/lint-python.yml

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          src: aegiscan/
          version: v0.9.1
          args: check --no-fix

      - uses: chartboost/ruff-action@v1
        with:
          src: aegiscan/
          version: v0.9.1
          args: format --diff
