name: Release

on:
  release:
    types:
      - created

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release Branch
        run: |
          git checkout -b release/${{ github.event.release.tag_name }}
          git push origin release/${{ github.event.release.tag_name }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge main into release branch
          base: release/${{ github.event.release.tag_name }}
          title: "release: ${{ github.event.release.tag_name }}"
          reviewers: topher-lo
          labels: release
          body: |
            This PR merges the latest changes from `main` into the release branch for version ${{ github.event.release.tag_name }}.

      - name: Output PR URL
        run: |
          echo "Pull request created: ${{ steps.create-pr.outputs.pull-request-url }}"
